services:
  integration-service:
    container_name: integration-service
    image: questions/integration-service
    mem_limit: 512m
    build:
      context: services/integration-service
      dockerfile: Dockerfile
    networks:
      - questions
    ports:
      - "8081:8081"

  product-service:
    container_name: product-service
    image: questions/product-service
    mem_limit: 512m
    build:
      context: services/product-service
      dockerfile: Dockerfile
    networks:
      - questions

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: questions-db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - questions
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - questions

networks:
  questions:
    driver: bridge
volumes:
  postgres:
    driver: local