spring:
  application:
    name: product-service
  grpc.server:
    port: 8081
    host: integration-service
  datasource:
    url: jdbc:postgresql://postgres:5432/questions-db
    password: password
    username: username
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: false