apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: questions
  labels:
    app: integration-service
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: integration-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
        - name: integration-service
          image: questions/integration-service
          imagePullPolicy: Never
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      tolerations:
        - key: "cattle.io/os"
          value: "linux"
          effect: "NoSchedule"
      volumes:
       - name: config-volume
         configMap:
           name: service-properties

---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: questions
  labels:
    app: integration-service
spec:
  type: LoadBalancer
  selector:
    app: integration-service
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8081