apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: questions
  labels:
    app: product-service
  annotations:
    fluxcd.io/tag.example-app: semver:~1.0
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: questions/product-service
          imagePullPolicy: Never
          volumeMounts:
            - name: config-volume
              mountPath: /configs/
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      tolerations:
        - key: "cattle.io/os"
          value: "linux"
          effect: "NoSchedule"
      volumes:
        - name: config-volume
          configMap:
            name: service-properties

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: questions
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081